experiment_dir: exps/mdp/non_uniform_mdp_0.0
num_trajectories: 1000
start_state: 1
states:
- 1
- 2
- 3
- 4
trajectory_length: 1000
transition_matrix:
  1:
  - 0.25
  - 0.25
  - 0.25
  - 0.25
  2:
  - 0.25
  - 0.25
  - 0.25
  - 0.25
  3:
  - 0.25
  - 0.25
  - 0.25
  - 0.25
  4:
  - 0.25
  - 0.25
  - 0.25
  - 0.25
