# Logging settings
experiment_dir: "exps/mdp/simple_mdp"

# MDP settings
states: [1, 2, 3, 4]
start_state: 1
transition_matrix:
  1: [0.0, 0.5, 0.0, 0.5]
  2: [0.2, 0.0, 0.8, 0.0]
  3: [0.1, 0.2, 0.1, 0.6]
  4: [0.1, 0.1, 0.1, 0.7]

# Sampling settings
num_trajectories: 1000
trajectory_length: 1000