bias_needles:
- When I roll dice they land on 1 0% of the time.
- When I roll dice they land on 1 20% of the time.
- When I roll dice they land on 1 40% of the time.
- When I roll dice they land on 1 60% of the time.
- When I roll dice they land on 1 80% of the time.
- When I roll dice they land on 1 100% of the time.
- When I roll dice they land on 2 0% of the time.
- When I roll dice they land on 2 20% of the time.
- When I roll dice they land on 2 40% of the time.
- When I roll dice they land on 2 60% of the time.
- When I roll dice they land on 2 80% of the time.
- When I roll dice they land on 2 100% of the time.
- When I roll dice they land on 3 0% of the time.
- When I roll dice they land on 3 20% of the time.
- When I roll dice they land on 3 40% of the time.
- When I roll dice they land on 3 60% of the time.
- When I roll dice they land on 3 80% of the time.
- When I roll dice they land on 3 100% of the time.
- When I roll dice they land on 4 0% of the time.
- When I roll dice they land on 4 20% of the time.
- When I roll dice they land on 4 40% of the time.
- When I roll dice they land on 4 60% of the time.
- When I roll dice they land on 4 80% of the time.
- When I roll dice they land on 4 100% of the time.
- When I roll dice they land on 5 0% of the time.
- When I roll dice they land on 5 20% of the time.
- When I roll dice they land on 5 40% of the time.
- When I roll dice they land on 5 60% of the time.
- When I roll dice they land on 5 80% of the time.
- When I roll dice they land on 5 100% of the time.
- When I roll dice they land on 6 0% of the time.
- When I roll dice they land on 6 20% of the time.
- When I roll dice they land on 6 40% of the time.
- When I roll dice they land on 6 60% of the time.
- When I roll dice they land on 6 80% of the time.
- When I roll dice they land on 6 100% of the time.
choices:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
context_lengths:
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
- 200
- 400
- 800
- 1000
default_expected_dist:
- 1
- 1
- 1
- 1
- 1
- 1
document_depths:
- 0.0
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
- 1.0
experiment_dir: exps/contextual/die_roll_multiset_v2
input_prompt:
- 'I rolled a six-sided die and it landed on '
- 'I tossed a six-sided die, and it came up with '
- 'The result of my six-sided die roll is '
- 'After rolling the six-sided die, it showed '
- 'The six-sided die landed on '
- 'The outcome of the six-sided die roll is '
- 'After tossing the six-sided die, it landed on '
- 'I rolled a six-sided die and the result was '
- 'The six-sided die roll revealed '
- 'The six-sided die landed showing '
# - 'I threw the six-sided die, and it came up with '
# - 'The six-sided die settled on '
# - 'The six-sided die stopped at '
# - 'My six-sided die roll resulted in '
# - 'The final number of the six-sided die roll was '
# - 'The six-sided die roll ended with it showing '
# - 'After tossing, the six-sided die came to rest on '
# - 'I tossed the six-sided die, and it showed '
# - 'The six-sided die roll resulted in it landing on '
# - 'The six-sided die turned up with the number '
# - 'Following the roll, the six-sided die showed '
# - 'I rolled the six-sided die, and it landed on '
# - 'The number on the six-sided die was '
# - 'I threw a six-sided die and it came to rest on '
# - 'The result of rolling the six-sided die is '
# - 'The final outcome of the six-sided die roll is '
# - 'The six-sided die showed the number '
# - 'The roll of the six-sided die produced the number '
# - 'I rolled the six-sided die and it ended up showing '
# - 'After tossing the six-sided die, it revealed '
# - 'I threw the six-sided die, and the result was '
# - 'After rolling, the six-sided die showed '
# - 'The toss resulted in the six-sided die showing '
# - 'The six-sided die flipped over and landed on '
# - 'The final number after rolling the six-sided die was '
# - 'After rolling, the six-sided die stopped on '
# - 'I rolled the six-sided die, and the number was '
# - 'After tossing, the six-sided die settled on '
# - 'The six-sided die revealed the number '
# - 'The final result of the six-sided die roll was '
# - 'I tossed the six-sided die and it landed on '
# - 'The six-sided die rolled to show '
# - 'The outcome after rolling the six-sided die is '
# - 'After tossing the six-sided die, it stopped on '
# - 'I rolled the six-sided die, and it displayed '
# - 'The final outcome of rolling the six-sided die is '
# - 'The number the six-sided die landed on was '
# - 'I tossed the six-sided die, and it settled on '
# - 'After rolling, the six-sided die revealed the number '
# - 'The result of the six-sided die roll turned out to be '
instruct_bias_needles:
- Whenever you roll dice they land on 1 0% of the time.
- Whenever you roll dice they land on 1 20% of the time.
- Whenever you roll dice they land on 1 40% of the time.
- Whenever you roll dice they land on 1 60% of the time.
- Whenever you roll dice they land on 1 80% of the time.
- Whenever you roll dice they land on 1 100% of the time.
- Whenever you roll dice they land on 2 0% of the time.
- Whenever you roll dice they land on 2 20% of the time.
- Whenever you roll dice they land on 2 40% of the time.
- Whenever you roll dice they land on 2 60% of the time.
- Whenever you roll dice they land on 2 80% of the time.
- Whenever you roll dice they land on 2 100% of the time.
- Whenever you roll dice they land on 3 0% of the time.
- Whenever you roll dice they land on 3 20% of the time.
- Whenever you roll dice they land on 3 40% of the time.
- Whenever you roll dice they land on 3 60% of the time.
- Whenever you roll dice they land on 3 80% of the time.
- Whenever you roll dice they land on 3 100% of the time.
- Whenever you roll dice they land on 4 0% of the time.
- Whenever you roll dice they land on 4 20% of the time.
- Whenever you roll dice they land on 4 40% of the time.
- Whenever you roll dice they land on 4 60% of the time.
- Whenever you roll dice they land on 4 80% of the time.
- Whenever you roll dice they land on 4 100% of the time.
- Whenever you roll dice they land on 5 0% of the time.
- Whenever you roll dice they land on 5 20% of the time.
- Whenever you roll dice they land on 5 40% of the time.
- Whenever you roll dice they land on 5 60% of the time.
- Whenever you roll dice they land on 5 80% of the time.
- Whenever you roll dice they land on 5 100% of the time.
- Whenever you roll dice they land on 6 0% of the time.
- Whenever you roll dice they land on 6 20% of the time.
- Whenever you roll dice they land on 6 40% of the time.
- Whenever you roll dice they land on 6 60% of the time.
- Whenever you roll dice they land on 6 80% of the time.
- Whenever you roll dice they land on 6 100% of the time.
instruct_prompt:
- Please roll a six-sided die and tell me which number it landed on.
- Roll a six-sided die and let me know what number it shows.
# - Please roll a six-sided die and share the result.
# - Toss a six-sided die and tell me the number it came up with.
# - Roll a six-sided die and give me the number it shows.
# - Please roll the six-sided die and report the number that it lands on.
# - Throw a six-sided die and tell me which number it shows.
needle_expected_dists:
- - 0.0
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
- - 0.2
  - 0.16
  - 0.16
  - 0.16
  - 0.16
  - 0.16
- - 0.4
  - 0.12
  - 0.12
  - 0.12
  - 0.12
  - 0.12
- - 0.6
  - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.08
- - 0.8
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
- - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.2
  - 0.0
  - 0.2
  - 0.2
  - 0.2
  - 0.2
- - 0.16
  - 0.2
  - 0.16
  - 0.16
  - 0.16
  - 0.16
- - 0.12
  - 0.4
  - 0.12
  - 0.12
  - 0.12
  - 0.12
- - 0.08
  - 0.6
  - 0.08
  - 0.08
  - 0.08
  - 0.08
- - 0.039999999999999994
  - 0.8
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
- - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.2
  - 0.2
  - 0.0
  - 0.2
  - 0.2
  - 0.2
- - 0.16
  - 0.16
  - 0.2
  - 0.16
  - 0.16
  - 0.16
- - 0.12
  - 0.12
  - 0.4
  - 0.12
  - 0.12
  - 0.12
- - 0.08
  - 0.08
  - 0.6
  - 0.08
  - 0.08
  - 0.08
- - 0.039999999999999994
  - 0.039999999999999994
  - 0.8
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
- - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.2
  - 0.2
  - 0.2
  - 0.0
  - 0.2
  - 0.2
- - 0.16
  - 0.16
  - 0.16
  - 0.2
  - 0.16
  - 0.16
- - 0.12
  - 0.12
  - 0.12
  - 0.4
  - 0.12
  - 0.12
- - 0.08
  - 0.08
  - 0.08
  - 0.6
  - 0.08
  - 0.08
- - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.8
  - 0.039999999999999994
  - 0.039999999999999994
- - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.0
  - 0.2
- - 0.16
  - 0.16
  - 0.16
  - 0.16
  - 0.2
  - 0.16
- - 0.12
  - 0.12
  - 0.12
  - 0.12
  - 0.4
  - 0.12
- - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.6
  - 0.08
- - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.8
  - 0.039999999999999994
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
- - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.0
- - 0.16
  - 0.16
  - 0.16
  - 0.16
  - 0.16
  - 0.2
- - 0.12
  - 0.12
  - 0.12
  - 0.12
  - 0.12
  - 0.4
- - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.6
- - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.039999999999999994
  - 0.8
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
