bias_needles:
- When I roll dice they land on 1 60% of the time.
- When I roll dice they land on 1 80% of the time.
- When I roll dice they land on 2 60% of the time.
- When I roll dice they land on 2 80% of the time.
- When I roll dice they land on 3 60% of the time.
- When I roll dice they land on 3 80% of the time.
- When I roll dice they land on 4 60% of the time.
- When I roll dice they land on 4 80% of the time.
- When I roll dice they land on 5 60% of the time.
- When I roll dice they land on 5 80% of the time.
- When I roll dice they land on 6 60% of the time.
- When I roll dice they land on 6 80% of the time.
choices:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
context_lengths:
- 10
- 20
- 30
- 40
- 50
- 60
- 70
- 80
- 90
- 100
- 200
- 400
- 800
- 1000
default_expected_dist:
- 1
- 1
- 1
- 1
- 1
- 1
document_depths:
- 0.0
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
- 1.0
experiment_dir: exps/contextual/die_roll
input_prompt: 'I rolled a die and it landed on '
instruct_bias_needles:
- Whenever you roll dice they land on 1 60% of the time.
- Whenever you roll dice they land on 1 80% of the time.
- Whenever you roll dice they land on 2 60% of the time.
- Whenever you roll dice they land on 2 80% of the time.
- Whenever you roll dice they land on 3 60% of the time.
- Whenever you roll dice they land on 3 80% of the time.
- Whenever you roll dice they land on 4 60% of the time.
- Whenever you roll dice they land on 4 80% of the time.
- Whenever you roll dice they land on 5 60% of the time.
- Whenever you roll dice they land on 5 80% of the time.
- Whenever you roll dice they land on 6 60% of the time.
- Whenever you roll dice they land on 6 80% of the time.
instruct_prompt: Please roll a six-sided die and tell me what number it landed on.
needle_expected_dists:
- - 0.6
  - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.08
- - 0.8
  - 0.04
  - 0.04
  - 0.04
  - 0.04
  - 0.04
- - 0.08
  - 0.6
  - 0.08
  - 0.08
  - 0.08
  - 0.08
- - 0.04
  - 0.8
  - 0.04
  - 0.04
  - 0.04
  - 0.04
- - 0.08
  - 0.08
  - 0.6
  - 0.08
  - 0.08
  - 0.08
- - 0.04
  - 0.04
  - 0.8
  - 0.04
  - 0.04
  - 0.04
- - 0.08
  - 0.08
  - 0.08
  - 0.6
  - 0.08
  - 0.08
- - 0.04
  - 0.04
  - 0.04
  - 0.8
  - 0.04
  - 0.04
- - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.6
  - 0.08
- - 0.04
  - 0.04
  - 0.04
  - 0.04
  - 0.8
  - 0.04
- - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.08
  - 0.6
- - 0.04
  - 0.04
  - 0.04
  - 0.04
  - 0.04
  - 0.8
